### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Your-First-iOS-App#2]
I need to figure out a license for this code. I don't expect anyone will package it to sell it, since it's open source, but I want to prevent it anyway. MIT? GPL? What?

**Comment by swizzlr** [comment]
Much as I despise the GPL you can use GPL2 for it. Or a Creative Commons non-commercial, non-derivative license.

**Comment by darrellwhitelaw** [comment]
Can't go wrong with MIT. 

## 

T9'd from my pocket

**Comment by swizzlr** [comment]
MIT is like BSD isn't it? That just requires attribution. Doesn't stop somebody from reselling.

**Comment by swizzlr** [comment]
Better idea: retain full copyright. Your own private use only. Just because you open source something doesn't mean it's other peoples'.

**Comment by einarvollset** [comment]
Ditto - keep the copyright. You can always open source it later.

**Comment by cwr** [comment]
I've never seen limitations put on example code in a book. I don't know if this format of publishing changes that in any way?

**Comment by cwr** [comment]
I should clarify my statement vibe never seen any license on the code included in a book beyond full attribution.

**Comment by swizzlr** [comment]
At the end of the day, Ash can do what he wants with it.

**Comment by cwr** [comment]
Of course he can. I question was asked about licensing and I added a comment.

**Comment by cwr** [comment]
Of course it's kind of crazy to write a book to learn from and create a license that precludes the learner from using the code in any way he/she desires as long as the source if said code is attributed which is why every book I can think of that I've bought goes this route.

The book content (sans source) is a completely different beast though and it should be clear that these pieces can not be redistributed.

**Comment by ashfurrow** [comment]
Yeah, I think we're clear on that: the book is under fully copyright. 

For the code, I'm imagining something where the readers can do whatever they want with it, but can't redistribute a binary under their own name, that's all. Everything else should be fair game. 

I'm talking with a lawyer now about the best approach, but I'm imagining something like BSD or Apache.

**Comment by cwr** [comment]
I'm not sure either of those licenses will meet your need...

OS X is built on extended BSD licensed code. Many of the commercial Hadoop implementations are built on extended Apache licensed code (vs done in a clean room fashion).

How do you define the cutoff? In a commercial app can the purchaser use x number of routines, x number of contiguous routines?

If the application your building in the book is something you don't wish re-distributed I'd suggest you choose another app to be safe.

I'm just trying to illuminate potential issues you'll have with a permissive license. A non-permissive license doesn't make much sense in the context of a book to learn from though.

Hopefully users will re-write code examples because they'll actually learn something which I'm not sure cutting and pasting allows for but cutting and pasting will be done and should be allowed.

But as one of the commenters on this thread has said it's your product so it's your decision.

**Comment by uraimo** [comment]
Considering the context where the code is presented (a book, an educational product) i'd recommend the usual 3-clause BSD (Ash,having that 3rd non-endorsement clause could make sense), where the only real requirement is the inclusion of the original license in any derived product (the Apache and MIT license has the same requirement).
Definitely no GPL in any form, it will scare away customers in professional context, gpl infection is quite scary for programmers that actually read licenses and try to follow what's written within.

**Comment by ashfurrow** [comment]
It came down to BSD 3-clause vs. full copyright. I'm not terribly worried someone is going to release a competing coffee timer, so BSD it is!
