### ISSUE TITLE
Problem with NSFetchedResultsController and Re-ordering cells

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/Your-First-iOS-App#3]
Whenever you re-order cells, there's a strange animation and trying to move a row from the top section down to the bottom section results in strange behaviour in the bottom section.

![ios simulator screen shot 2013-05-11 5 26 54 pm](https://f.cloud.github.com/assets/498212/492134/a45088d0-ba81-11e2-86f2-345d26a32abc.png)

My fetched results controller delegate methods are very straightforward. The key one is this: 

```
- (void)controller:(NSFetchedResultsController *)controller
   didChangeObject:(id) anObject
       atIndexPath:(NSIndexPath *)indexPath
     forChangeType:(NSFetchedResultsChangeType)type
      newIndexPath:(NSIndexPath *)newIndexPath
{
    switch(type)
    {
        case NSFetchedResultsChangeInsert:
            [self.tableView insertRowsAtIndexPaths:@[newIndexPath]
                                  withRowAnimation:UITableViewRowAnimationAutomatic];
            break;
        case NSFetchedResultsChangeDelete:
            [self.tableView deleteRowsAtIndexPaths:@[indexPath]
                                  withRowAnimation:UITableViewRowAnimationAutomatic];
            break;
        case NSFetchedResultsChangeUpdate:
            [self.tableView reloadRowsAtIndexPaths:@[indexPath]
                                  withRowAnimation:UITableViewRowAnimationAutomatic];
            break;
        case NSFetchedResultsChangeMove:
            [self.tableView moveRowAtIndexPath:indexPath toIndexPath:newIndexPath];
            break;
    }
}
```

My re-ordering code is below:

```
 - (void)tableView:(UITableView *)tableView
moveRowAtIndexPath:(NSIndexPath *)sourceIndexPath
       toIndexPath:(NSIndexPath *)destinationIndexPath
{
    NSMutableArray *sectionObjects = [[[self.fetchedResultsController sections][sourceIndexPath.section] objects] mutableCopy];

    // Grab the item we're moving.
    NSManagedObject *movedObject = [[self fetchedResultsController] objectAtIndexPath:sourceIndexPath];

    // Remove the object we're moving from the array.
    [sectionObjects removeObject:movedObject];
    // Now re-insert it at the destination.
    [sectionObjects insertObject:movedObject atIndex:destinationIndexPath.row];

    // All of the objects are now in their correct order. Update each
    // object's displayOrder field by iterating through the array.
    for (NSInteger i = 0; i < sectionObjects.count; i++)
    {
        CTRTimerModel *model = sectionObjects[i];
        model.displayOrder = i;
    }

    [movedObject.managedObjectContext save:nil];
}
```

Anyone have any ideas?

**Comment by pgor** [comment]
You need to ignore -controller:didChangeObject: calls that are due to user interaction. The tableView has already adjusted its cell indexPaths, so doing it again is just going to mess things up because the cells in question are no longer "there". As much as I hate boolean state properties like this, the simplest solution seems to be to create a BOOL reordering property that you set YES just before saving and NO right after. In -controller:didChangeObject: just early return if isReordering.

Another trick I've learned is to use a float for displayOrder. When inserting an object, you can just split the difference of the surrounding objects' displayOrder values and not have to update the whole list. At some point in the future, you can take the time to normalize them all back out to single-steps if you wish.
